const Images={
    image1:require('./images/videobg.jpg').default,
    image2:require('./images/6.jpg').default,
    bassam:require('./images/bassam.jpg').default,
    sabbah:require('./images/Abdelrahman Al-Sabbah.jpg').default,
    hussien:require('./images/hussien seif .jpg').default,
    zayan:require('./images/khalil.jpg').default,
    essam:require('./images/essam.jpg').default,
    fouda:require('./images/ahmed fouda.png').default,
    sameh:require('./images/abo.jpg').default,
    nessren:require('./images/nessren.jpg').default,
    salma:require('./images/salma.jpg').default,
    attia:require('./images/a1.jpg').default,
    samee:require('./images/a2.jpg').default,
    khalil:require('./images/a3.jpg').default,
    oraby:require('./images/mahmoud aloraby.jpg').default,
    waref:require('./images/waref.jpg').default,
    dalia:require('./images/dalia.jpg').default,
    rasesh:require('./images/rasesh.jpg').default,
    abdelbaset:require('./images/abdelbaset.jpg').default,
    sara:require('./images/sara.jpg').default,
    adel:require('./images/mohamed adel.jpg').default,
    ashraf:require('./images/ashraf.jpg').default,
    khalifa:require('./images/khalifa2.jpg').default,
    rashed:require('./images/rashed.jpg').default,
    othman:require('./images/othman.jpg').default,
    mohamed:require('./images/mg.jpg').default,
    eslam:require('./images/eg.jpg').default,
    ghazal:require('./images/ghazal.jpg').default,
    saad:require('./images/saad.jpg').default,
    assem:require('./images/assem.jpg').default,
    ebeda:require('./images/3ebeda.jpg').default,  
}
export default Images;